### ISSUE TITLE
'Update product' action renders recurring coupons useless

### ISSUE THREAD

**Issue by jrick1229** [Prospress/automatewoo-subscriptions#29] opened 2019-08-07 17:24 UTC
@danielbitzer: **STATUS:** This change is dependent on WC 3.8 and AW 4.8.

### Issue

If a subscription has an applied recurring coupon, the discount is not calculated when the 'Update product' option is used to alter the recurring price of the subscription.

### Steps to Replicate

1. Create a subscription product.
   - $500 every month
2. Create a recurring coupon.
   - Recurring Product % Discount
   - Coupon amount: 10
3. Create a new workflow.
   - Trigger: Subscription renewal complete
   - Rules: none
   - Action: Update Product
      - Custom Product Price: 200.00
4. Purchase the new subscription product with the newly created coupon.
5. Navigate to the subscription in the /wp-admin.
6. Process a renewal.

Once the renewal is processed and the workflow has run, you'll see that the new subscription total is $200.00. The coupon is still attached to the subscription, but it ultimately does nothing to discount the total.

### Additional Comments

Similar to the 'Update Schedule' action, which has a 'Recalculate Dates' option, I feel that a 'Recalculate Totals' option could be beneficial in this action.

For now, I've recommended that they use a Rule, alongside having more than just the one workflow, which will adjust the price of the product depending on what type of coupon is used. This does what they basically want, but also requires a workflow for each coupon discount amount.

**Comment by thenbrent** [comment] 2019-08-08 00:44
> I feel that a 'Recalculate Totals' option could be beneficial in this action.

Agreed. For this case though, the [totals are being recalculated](https://github.com/Prospress/automatewoo-subscriptions/blob/master/includes/actions/update-product.php#L124), so I'm not sure why the coupons aren't being applied. Possibly because [the `subtotal` is being set explicitly](https://github.com/Prospress/automatewoo-subscriptions/blob/master/includes/actions/update-product.php#L111).

**Comment by danbitzer** [comment] 2019-10-04 01:47
We've just had another report of this. At first glance it looks like `\WC_Abstract_Order::calculate_totals` doesn't recalculate the subscription's discount amounts. 

It sounds like we could add a 'Recalculate discounts' checkbox to the action. Although, are there really any cases where you wouldn't want to recalculate the discount amounts?

**Comment by thenbrent** [comment] 2019-10-04 03:03
> Although, are there really any cases where you wouldn't want to recalculate the discount amounts?

I wouldn't think so. Which is why it's so surprising to me that `\WC_Abstract_Order` doesn't recalculate them. It may just be an oversight?

> it looks like `\WC_Abstract_Order::calculate_totals` doesn't recalculate the subscription's discount amounts.

It also looks like the methods that could be used by a 3rd party to recalculate discounts are `protected`. Namely `\WC_Abstract_Order::recalculate_coupons`.

That could be changed in WC Core or in Subscriptions. We could potentially even call `\WC_Abstract_Order::recalculate_coupons` in `\WC_Subscription::calculate_totals`, because like you say, I can't see any cases where you wouldn't want to recalculate the discount amounts for a subscription. /cc @james-allan on that.

**Comment by danbitzer** [comment] 2019-10-04 05:11
> I wouldn't think so. Which is why it's so surprising to me that \WC_Abstract_Order doesn't recalculate them. It may just be an oversight?

This might be to prevent issues if the coupon was changed, deleted or maybe if coupon has expired it would be removed during recalculation?

**Comment by danbitzer** [comment] 2019-10-04 07:25
It looks like if a coupon is deleted `recalculate_coupons` can use the stored coupon data from order item meta so that isn't an issue.

However, coupons do appear to be re-validated which likely means any expired coupons would be removed. It also might mean that coupons restricted to one use per customer would be removed.

**Comment by james-allan** [comment] 2019-10-24 01:46
> We could potentially even call `\WC_Abstract_Order::recalculate_coupons` in `\WC_Subscription::calculate_totals`, because like you say, I can't see any cases where you wouldn't want to recalculate the discount amounts for a subscription.

We haven't overridden that function in `WC_Subscription` so we'd need to do that and basically just duplicate the `WC_Abstract_Order` implementation and add the recalculate discounts line. 

Something else to keep in mind. `WC_Abstract_Order::recalculate_coupons()` also calls [`calculate_totals()` ](https://github.com/woocommerce/woocommerce/blob/3.7.1/includes/abstracts/abstract-wc-order.php#L1130)so we'd end up in an infinite loop. 

Idk about doing this honestly. I think this might be by design and not an oversight.

`calculate_totals()` just recalculates the grand totals - taxes, shipping line item total, line item subtotal and total discount. Because coupons apply to the line item amounts, it's another function that needs to run those coupon calculations, to update the line items before `calculate_totals()` is called.

**Comment by thenbrent** [comment] 2019-10-24 01:51
> Because coupons apply to the line item amounts, it's another function that needs to run those coupon calculations, to update the line items before `calculate_totals()` is called.

The same thing is true for taxes, but `calculate_totals()` calls `calculate_taxes()`.

**Comment by james-allan** [comment] 2019-10-24 03:03
> The same thing is true for taxes, but calculate_totals() calls calculate_taxes().

Yeah that's true, however, taxes are a little different in my opinion.

Taxes need to be recalculated if: 

1. The billing address changes. 
1. The tax rates change - new rates and/or updated rates. 
1. The line items change:
    1. The products change.
    1. The shipping changes.
    1. The fees change.
 1. or all of the above.

Whereas discounts need recalculating if:

1. The line item changes.
1. A coupon is removed
1. A coupon is added.

Both [adding](https://github.com/woocommerce/woocommerce/blob/3.7.1/includes/abstracts/abstract-wc-order.php#L1027) and [removing](https://github.com/woocommerce/woocommerce/blob/3.7.1/includes/abstracts/abstract-wc-order.php#L1065) coupons recalculate discounts automatically so there's isn't as much of a need to recalculate the coupons every time the order totals are calculated. There are just fewer pathways which lead to a need for them to be recalculated.

Having said that, I could see them doing something similar with coupons. That's to say add a param to `calculate_totals()` and if it's true, recalculate coupons.

OR 

When you update a line item's total, it recalculates the discounts. 

The bad news is that the recalculate discounts function is protected so from AW there aren't really many other options. 🤔

**Comment by james-allan** [comment] 2019-10-24 03:21
> The bad news is that the recalculate discounts function is protected so from AW there aren't really many other options.

I've had a look and there really are none. AW or Subscriptions would need to introduce a function which is basically a public wrapper of `WC_Abstract_Order::recalculate_coupons()` or duplicate of that function. 

The other hacky option I can see is remove a coupon and then readd it to trigger WC to recalculate the discounts. 

IMO there should really be a publically available function to do this though whether that's an updated `calculate_totals()` function or a public `WC_Abstract_Order::recalculate_coupons()`

**Comment by danbitzer** [comment] 2019-10-24 04:10
Thanks for having a look @james-allan!

I agree the method should not be protected in WC core. Even for orders you could add/edit a an order line item (if it's not paid) and then coupons _should_ be recalculated. I guess I'll need to open a PR.

**Comment by danbitzer** [comment] 2019-10-24 23:18
So it's already being made public in 3.8 🎉 
https://github.com/woocommerce/woocommerce/commit/8c88cd9b6f133aa05ad01862b7aa2d8927b16be0

**Comment by danbitzer** [comment] 2019-10-24 23:41
Do you think it also makes sense to call `recalculate_coupons` after shipping is changed by an AW action?

I think yes since a coupon may have a shipping discount.

**Comment by danbitzer** [comment] 2020-05-01 07:29
Fixed in 1.0.3 🎉

**Closed as completed by danbitzer** 2020-05-01 07:29 UTC
Labels: type: bug, needs investigation
